"""Cash Voucher PDF — generated by Accounting for a paid Payment Request."""

import os
import logging

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    BaseDocTemplate, Frame, Image, PageTemplate,
    Table, TableStyle, Paragraph, Spacer,
)
from reportlab.lib.styles import ParagraphStyle
from dateutil.parser import parse as dateutil_parse

from pdf_generators.utils import get_static_path

logger = logging.getLogger(__name__)

BRAND_BLUE  = colors.HexColor("#1e40af")
BRAND_AMBER = colors.HexColor("#d97706")
HEADER_BG   = colors.HexColor("#1e3a5f")
HEADER_TEXT = colors.white
ROW_ALT     = colors.HexColor("#f8fafc")
BORDER_COL  = colors.HexColor("#cbd5e1")


def _fmt_date(raw):
    if not raw:
        return ""
    try:
        return dateutil_parse(str(raw)).strftime("%B %d, %Y")
    except Exception:
        return str(raw)


def _fmt_currency(raw):
    if not raw:
        return ""
    try:
        return f"{float(str(raw).replace(',', '')):,.2f}"
    except (ValueError, TypeError):
        return str(raw)


def build_cash_voucher_pdf(buffer, pr_details: dict, cv_details: dict):
    """Build a Cash Voucher PDF.

    Args:
        buffer:     BytesIO to write into
        pr_details: Payment Request fields (same shape as billing record)
        cv_details: Cash Voucher specific fields:
                      cv_number, cv_date, prepared_by, approved_by,
                      account_charged, particulars, debit_amount,
                      credit_account, payment_mode, cheque_number,
                      cheque_date, bank_name, additional_notes
    """
    PAGE_W, PAGE_H = A4

    doc = BaseDocTemplate(
        buffer, pagesize=A4,
        leftMargin=0.6 * inch, rightMargin=0.6 * inch,
        topMargin=0.5 * inch, bottomMargin=0.5 * inch,
    )
    frame_w = PAGE_W - doc.leftMargin - doc.rightMargin

    cv_no = cv_details.get("cv_number", "")
    pr_no = pr_details.get("pr_number", "")

    def _on_page(canvas, doc_obj):
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(colors.HexColor("#94a3b8"))
        canvas.drawCentredString(
            PAGE_W / 2, 0.3 * inch,
            f"Cash Voucher {cv_no}  |  PR Ref: {pr_no}"
        )
        canvas.restoreState()

    doc.addPageTemplates([
        PageTemplate(
            id="Main",
            frames=[Frame(doc.leftMargin, doc.bottomMargin,
                          frame_w, PAGE_H - doc.topMargin - doc.bottomMargin,
                          id="content")],
            onPage=_on_page,
        )
    ])

    elements = []

    ls = ParagraphStyle("lbl", fontName="Helvetica-Bold", fontSize=8.5,
                         textColor=colors.HexColor("#334155"), leading=11)
    vs = ParagraphStyle("val", fontName="Helvetica", fontSize=9,
                         textColor=colors.black, leading=12)
    sts = ParagraphStyle("sec", fontName="Helvetica-Bold", fontSize=10,
                          textColor=BRAND_BLUE, leading=14, spaceAfter=4)

    # ── Logo + Title ────────────────────────────────────────────
    logo_path = get_static_path("images", "logo.png")
    logo_cell = Paragraph("", vs)
    if os.path.exists(logo_path):
        try:
            logo_cell = Image(logo_path, width=2.0 * inch, height=0.56 * inch)
        except Exception:
            pass

    title_style = ParagraphStyle(
        "t", fontName="Helvetica-Bold", fontSize=18,
        textColor=BRAND_AMBER, alignment=2, leading=22,
    )
    sub_style = ParagraphStyle(
        "s", fontName="Helvetica", fontSize=9,
        textColor=colors.HexColor("#475569"), alignment=2, leading=13,
    )

    hdr = Table(
        [[logo_cell, [
            Paragraph("CASH VOUCHER", title_style),
            Paragraph(f"CV No.: {cv_no}  |  PR Ref: {pr_no}", sub_style),
        ]]],
        colWidths=[frame_w * 0.45, frame_w * 0.55],
    )
    hdr.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING",  (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
    ]))
    elements.append(hdr)
    elements.append(Spacer(1, 0.12 * inch))

    # Amber divider
    div = Table([[""]], colWidths=[frame_w], rowHeights=[3])
    div.setStyle(TableStyle([
        ("LINEABOVE", (0, 0), (-1, 0), 3, BRAND_AMBER),
        ("TOPPADDING",    (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    elements.append(div)
    elements.append(Spacer(1, 0.18 * inch))

    # ── Helper: 2-column section ─────────────────────────────────
    def _section(title, rows):
        elements.append(Paragraph(title, sts))
        elements.append(Spacer(1, 0.04 * inch))
        table_rows = []
        for idx in range(0, len(rows), 2):
            left  = rows[idx]
            right = rows[idx + 1] if idx + 1 < len(rows) else ("", "")
            table_rows.append([
                Paragraph(left[0],              ls),
                Paragraph(str(left[1] or ""),  vs),
                Paragraph(right[0],             ls),
                Paragraph(str(right[1] or ""), vs),
            ])
        cw = frame_w / 4
        t = Table(table_rows, colWidths=[cw * 0.8, cw * 1.2, cw * 0.8, cw * 1.2])
        cmds = [
            ("VALIGN",        (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING",   (0, 0), (-1, -1), 6),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 6),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LINEBELOW",     (0, 0), (-1, -1), 0.5, BORDER_COL),
        ]
        for i in range(len(table_rows)):
            if i % 2 == 0:
                cmds.append(("BACKGROUND", (0, i), (-1, i), ROW_ALT))
        t.setStyle(TableStyle(cmds))
        elements.append(t)
        elements.append(Spacer(1, 0.18 * inch))

    # ── Voucher Details ──────────────────────────────────────────
    _section("VOUCHER DETAILS", [
        ("CV Number:",     cv_no),
        ("CV Date:",       _fmt_date(cv_details.get("cv_date", ""))),
        ("Prepared by:",   cv_details.get("prepared_by", "")),
        ("Approved by:",   cv_details.get("approved_by", "")),
    ])

    # ── Payee & PR Info ──────────────────────────────────────────
    _section("PAYEE & REQUEST DETAILS", [
        ("PR Number:",     pr_no),
        ("Request Date:",  _fmt_date(pr_details.get("request_date", ""))),
        ("Payee Name:",    pr_details.get("payee_name", "")),
        ("Payee Type:",    pr_details.get("payee_type", "")),
        ("Bank Name:",     pr_details.get("bank_name", "")),
        ("Account Name:",  pr_details.get("account_name", "")),
        ("Account No.:",   pr_details.get("account_number", "")),
        ("Purpose:",       pr_details.get("purpose", "")),
    ])

    # ── Journal Entry ────────────────────────────────────────────
    elements.append(Paragraph("JOURNAL ENTRY", sts))
    elements.append(Spacer(1, 0.05 * inch))

    currency     = pr_details.get("currency", "PHP")
    amount_fmt   = _fmt_currency(pr_details.get("amount", ""))
    acct_charged = cv_details.get("account_charged", "")
    particulars  = cv_details.get("particulars", pr_details.get("purpose", ""))
    debit_amt    = _fmt_currency(cv_details.get("debit_amount", pr_details.get("amount", "")))
    credit_acct  = cv_details.get("credit_account", "Cash / Bank")

    je_header = [
        Paragraph("Account",       ParagraphStyle("jh", fontName="Helvetica-Bold", fontSize=8.5, textColor=HEADER_TEXT)),
        Paragraph("Particulars",   ParagraphStyle("jh", fontName="Helvetica-Bold", fontSize=8.5, textColor=HEADER_TEXT)),
        Paragraph("Debit",         ParagraphStyle("jh", fontName="Helvetica-Bold", fontSize=8.5, textColor=HEADER_TEXT, alignment=2)),
        Paragraph("Credit",        ParagraphStyle("jh", fontName="Helvetica-Bold", fontSize=8.5, textColor=HEADER_TEXT, alignment=2)),
    ]
    je_rows = [
        je_header,
        [
            Paragraph(acct_charged or "Expense Account", vs),
            Paragraph(particulars, vs),
            Paragraph(f"{currency} {debit_amt}", ParagraphStyle("jv", fontName="Helvetica", fontSize=9, alignment=2, leading=12)),
            Paragraph("", vs),
        ],
        [
            Paragraph(credit_acct, vs),
            Paragraph("Payment released", vs),
            Paragraph("", vs),
            Paragraph(f"{currency} {amount_fmt}", ParagraphStyle("jv2", fontName="Helvetica", fontSize=9, alignment=2, leading=12)),
        ],
    ]
    je_col_w = [frame_w * 0.22, frame_w * 0.38, frame_w * 0.2, frame_w * 0.2]
    je_table = Table(je_rows, colWidths=je_col_w)
    je_table.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), HEADER_BG),
        ("TEXTCOLOR",     (0, 0), (-1, 0), HEADER_TEXT),
        ("BACKGROUND",    (0, 2), (-1, 2), ROW_ALT),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LINEBELOW",     (0, 0), (-1, -1), 0.5, BORDER_COL),
        ("BOX",           (0, 0), (-1, -1), 0.5, BORDER_COL),
    ]))
    elements.append(je_table)
    elements.append(Spacer(1, 0.18 * inch))

    # ── Payment Mode ─────────────────────────────────────────────
    payment_mode  = cv_details.get("payment_mode", pr_details.get("payment_method", ""))
    cheque_number = cv_details.get("cheque_number", "")
    cheque_date   = cv_details.get("cheque_date", "")
    bank          = cv_details.get("bank_name", pr_details.get("bank_name", ""))

    pm_rows = [("Payment Mode:", payment_mode), ("Bank:", bank)]
    if cheque_number:
        pm_rows += [("Cheque No.:", cheque_number), ("Cheque Date:", _fmt_date(cheque_date))]
    _section("PAYMENT MODE", pm_rows)

    # ── Additional Notes ─────────────────────────────────────────
    notes = (cv_details.get("additional_notes", "") or "").strip()
    if notes:
        elements.append(Paragraph("ADDITIONAL NOTES", sts))
        elements.append(Spacer(1, 0.04 * inch))
        elements.append(Paragraph(notes, ParagraphStyle(
            "notes", fontName="Helvetica", fontSize=9, textColor=colors.black,
            leading=13, backColor=colors.HexColor("#fffbeb"), borderPadding=8,
        )))
        elements.append(Spacer(1, 0.2 * inch))

    # ── Signatures ───────────────────────────────────────────────
    elements.append(Spacer(1, 0.35 * inch))

    sig_lbl = ParagraphStyle("sl", fontName="Helvetica-Bold", fontSize=8,
                              textColor=colors.HexColor("#475569"))
    sig_nm  = ParagraphStyle("sn", fontName="Helvetica", fontSize=9,
                              textColor=colors.black, alignment=1)
    sig_ps  = ParagraphStyle("sp", fontName="Helvetica-Oblique", fontSize=7.5,
                              textColor=colors.HexColor("#64748b"), alignment=1)
    lw = 1.7 * inch

    def _sig(label, name="", pos=""):
        uline = Table([[""]], colWidths=[lw], rowHeights=[0.5])
        uline.setStyle(TableStyle([
            ("LINEABOVE", (0, 0), (-1, 0), 0.5, colors.black),
            ("TOPPADDING",    (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]))
        t = Table([
            [Spacer(1, 0.35 * inch)],
            [uline],
            [Paragraph(name or "&nbsp;", sig_nm)],
            [Paragraph(pos  or "&nbsp;", sig_ps)],
            [Spacer(1, 0.04 * inch)],
            [Paragraph(f"<b>{label}</b>", sig_lbl)],
        ], colWidths=[lw])
        t.setStyle(TableStyle([
            ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
            ("TOPPADDING",    (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ("LEFTPADDING",   (0, 0), (-1, -1), 0),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 0),
        ]))
        return t

    sig_row = Table([[
        _sig("Prepared by:",    cv_details.get("prepared_by", ""), "Accounting"),
        _sig("Approved by:",    cv_details.get("approved_by", ""), "Management"),
        _sig("Received by:",    pr_details.get("payee_name", ""), pr_details.get("payee_type", "")),
    ]], colWidths=[frame_w / 3] * 3)
    sig_row.setStyle(TableStyle([
        ("ALIGN",  (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "BOTTOM"),
        ("LEFTPADDING",  (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(sig_row)

    doc.build(elements)
